# services to handle doctrine extensions
# import it in config.yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    # KernelRequest listener
    AppBundle\Listener\DoctrineExtensionListener:
    #extension.listener:
        #class: AppBundle\Listener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ "@service_container" ] ]
        tags:
            # translatable sets locale after router processing
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
            # loggable hooks user username if one is in security context
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            # translatable sets locale such as page application locale before command execute
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand, priority: -10 }


    # Doctrine Extension listeners to handle behaviors
    Gedmo\Tree\TreeListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    #gedmo.listener.translatable:
        #class: Gedmo\Translatable\TranslatableListener
    Gedmo\Translatable\TranslatableListener:
        #shared: false
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
             - [ setAnnotationReader, [ "@annotation_reader" ] ]
             - [ setDefaultLocale, [ "%locale%" ] ]
             - [ setTranslationFallback, [ false ] ]
    Gedmo\Loggable\LoggableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
             - [ setAnnotationReader, [ "@annotation_reader" ] ]